appName : pCTR
local : true
spark_dir : resources/spark/
connector : resources/ecosystem/spark/spark-tensorflow-connector/target/spark-tensorflow-connector_2.12-1.11.0.jar
root_dir : /home1/irteam/juhochoi/
spark_home_dir : resources/spark/
data_dir : data/criteo/
target_dir : train/
schema_file : schema.json
metadata_file : metadata.json
